### ISSUE TITLE
rename.lua can not input chinese characters, although show chinese character is fine

### ISSUE THREAD

**Issue by royaso** [CogentRedTester/mpv-user-input#5]

**Comment by CogentRedTester** [comment]
How are you trying to type in characters?

**Comment by royaso** [comment]
I use RIME squirrel to input chinese character. not worked.
then, I changed to macos system provided chinese input method, not worked neither.

then, I tried to paste some chinese characters into it.
just some '?' question marks show up.

after hitting enter, only '?'question marks show up in vedio file name.

only happens when I tried to input chinese words, but english letters works fine.

rename.lua is the only mpv plugin that can rename currently playing vedio file I can find. But without being able to input chinese characters, It would be useless.

please help.

**Comment by CogentRedTester** [comment]
The text input used by user-input is not a usual text box, it uses the raw key inputs sent to the mpv window, which may not work with the software you're using. It uses the same code as [console.lua](https://mpv.io/manual/master/#console), an inbuilt mpv script that uses an input box for sending commands to mpv. Improving support of the input box for unicode characters is beyond the scope of this script, but you are welcome to make the request on the main [mpv player repository](https://github.com/mpv-player/mpv). I add any changes to console.lua to this script to maintain consistency.

On windows, I did manage to type in characters by launching mpv from the terminal and typing into there, so that is an option:

![image](https://user-images.githubusercontent.com/57207260/165244225-bacbc37f-75f3-4ffe-852e-0f3500b41679.png)

Copying and pasting also worked for me on windows, it should be working for you, but if it's not then it might be a problem with the copy/paste code on MacOS. I don't have a MacOS device, so I can't test, but that would probably be a valid bug report to file on [mpv-player/mpv](https://github.com/mpv-player/mpv).

**Comment by royaso** [comment]
Thanks a lot!

I tried to  use mpv in terminal this time, still not able to input chinese characters, but when I pasted chinese character, It show up! 

I guess that is what I have to do.

thanks.

**Comment by CogentRedTester** [comment]
Do note that the paste not working from the window *is* a bug worth reporting to the mpv developers, I'd look into it myself if I had a MacOS device.

**Comment by royaso** [comment]
I dont know how to report to mpv developers.
it is very kind of you for doing that.
